# Generated by Django 5.1.1 on 2024-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0002_contadordata_luminosidadedata_temperaturadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umidadedata',
            name='tipo',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
