# Generated by Django 5.1.1 on 2024-10-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0003_umidadedata_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umidadedata',
            name='tipo',
        ),
    ]
